### ISSUE TITLE
KVS server throws zmq error after the routing node fails

### ISSUE THREAD

**Issue by cw75** [hydro-project/cloudburst#20]

**Comment by vsreekanti** [comment]
This is not related to Cloudburst at all. The reason this happens is because the routing node fails when it gets a request for an empty key (need to fix), the management server makes a synchronous no-timeout request to the routing tier (need to fix), and the KVS server makes a synchronous request to the management server. 

Checking for an empty response in Cloudburst wasn't happening before (which is why the empty key request was happening) has been fixed. Will open corresponding issues in other repos.
